In [1]:
pip install pandas numpy matplotlib openpyxl

Requirement already satisfied: pandas in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (2.2.5)
Requirement already satisfied: matplotlib in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: openpyxl in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: et-xmlfile in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\mangali\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# NovaMart Supply Chain Analytics

## Phase 2: Data Profiling

### Objective
Understand the dataset structure, identify data quality issues, and prepare the data for cleaning and business analysis.

In [2]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Mangali\NovaMart-SupplyChain-Analytics\data\raw\DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [11]:
rows, cols = df.shape

print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {cols}")

Number of Rows    : 180519
Number of Columns : 53

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

### Observations

- Dataset contains 180,520 records.
- Total columns: 53.
- Multiple numerical and categorical columns.
- Order Date and Shipping Date are stored as object (text).

In [5]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [6]:
df.describe(include="object")

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Lname,Customer Password,Customer Segment,...,Order City,Order Country,order date (DateOrders),Order Region,Order State,Order Status,Product Image,Product Name,shipping date (DateOrders),Shipping Mode
count,180519,180519,180519,180519,180519,180519,180519,180511,180519,180519,...,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519
unique,4,4,50,563,2,1,782,1109,1,3,...,3597,164,65752,23,1089,9,118,118,63701,4
top,DEBIT,Late delivery,Cleats,Caguas,EE. UU.,XXXXXXXXX,Mary,Smith,XXXXXXXXX,Consumer,...,Santo Domingo,Estados Unidos,1/4/2017 2:28,Central America,Inglaterra,COMPLETE,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,4/17/2015 22:16,Standard Class
freq,69295,98977,24551,66770,111146,180519,65150,64104,180519,93504,...,2211,24840,5,28341,6722,59491,24515,24515,10,107752

In [7]:
missing = df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

Product Description    180519
Order Zipcode          155679
Customer Lname              8
Customer Zipcode            3
dtype: int64

In [13]:
missing_df = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum()/len(df))*100
})

missing_df = missing_df[missing_df["Missing Values"] > 0]

missing_df.sort_values("Missing Percentage", ascending=False)

                     Missing Values  Missing Percentage
Product Description          180519          100.000000
Order Zipcode                155679           86.239676
Customer Lname                    8            0.004432
Customer Zipcode                  3            0.001662

In [18]:
df.dtypes.value_counts()

object     24
float64    15
int64      14
Name: count, dtype: int64

In [8]:
quality = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing %": round(df.isnull().mean()*100,2),
    "Data Type": df.dtypes
})

quality

                               Missing Values  Missing % Data Type
Type                                        0       0.00    object
Days for shipping (real)                    0       0.00     int64
Days for shipment (scheduled)               0       0.00     int64
Benefit per order                           0       0.00   float64
Sales per customer                          0       0.00   float64
Delivery Status                             0       0.00    object
Late_delivery_risk                          0       0.00     int64
Category Id                                 0       0.00     int64
Category Name                               0       0.00    object
Customer City                               0       0.00    object
Customer Country                            0       0.00    object
Customer Email                              0       0.00    object
Customer Fname                              0       0.00    object
Customer Id                                 0       0.00     int64
Customer Lname                              8       0.00    object
Customer Password                           0       0.00    object
Customer Segment                            0       0.00    object
Customer State                              0       0.00    object
Customer Street                             0       0.00    object
Customer Zipcode                            3       0.00   float64
Department Id                               0       0.00     int64
Department Name                             0       0.00    object
Latitude                                    0       0.00   float64
Longitude                                   0       0.00   float64
Market                                      0       0.00    object
Order City                                  0       0.00    object
Order Country                               0       0.00    object
Order Customer Id                           0       0.00     int64
order date (DateOrders)                     0       0.00    object
Order Id                                    0       0.00     int64
Order Item Cardprod Id                      0       0.00     int64
Order Item Discount                         0       0.00   float64
Order Item Discount Rate                    0       0.00   float64
Order Item Id                               0       0.00     int64
Order Item Product Price                    0       0.00   float64
Order Item Profit Ratio                     0       0.00   float64
Order Item Quantity                         0       0.00     int64
Sales                                       0       0.00   float64
Order Item Total                            0       0.00   float64
Order Profit Per Order                      0       0.00   float64
Order Region                                0       0.00    object
Order State                                 0       0.00    object
Order Status                                0       0.00    object
Order Zipcode                          155679      86.24   float64
Product Card Id                             0       0.00     int64
Product Category Id                         0       0.00     int64
Product Description                    180519     100.00   float64
Product Image                               0       0.00    object
Product Name                                0       0.00    object
Product Price                               0       0.00   float64
Product Status                              0       0.00     int64
shipping date (DateOrders)                  0       0.00    object
Shipping Mode                               0       0.00    object

In [14]:
unique_values = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[col].nunique() for col in df.columns]
})

unique_values.sort_values("Unique Values")

                           Column  Unique Values
46            Product Description              0
15              Customer Password              1
50                 Product Status              1
11                 Customer Email              1
6              Late_delivery_risk              2
10               Customer Country              2
16               Customer Segment              3
5                 Delivery Status              4
2   Days for shipment (scheduled)              4
52                  Shipping Mode              4
0                            Type              4
24                         Market              5
36            Order Item Quantity              5
1        Days for shipping (real)              7
42                   Order Status              9
20                  Department Id             11
21                Department Name             11
32       Order Item Discount Rate             18
40                   Order Region             23
17                 Customer State             46
8                   Category Name             50
45            Product Category Id             51
7                     Category Id             51
34       Order Item Product Price             75
49                  Product Price             75
47                  Product Image            118
44                Product Card Id            118
48                   Product Name            118
30         Order Item Cardprod Id            118
35        Order Item Profit Ratio            162
26                  Order Country            164
37                          Sales            193
9                   Customer City            563
43                  Order Zipcode            609
12                 Customer Fname            782
19               Customer Zipcode            995
31            Order Item Discount           1017
41                    Order State           1089
14                 Customer Lname           1109
38               Order Item Total           2927
4              Sales per customer           2927
25                     Order City           3597
23                      Longitude           4487
18                Customer Street           7458
22                       Latitude          11250
13                    Customer Id          20652
27              Order Customer Id          20652
3               Benefit per order          21998
39         Order Profit Per Order          21998
51     shipping date (DateOrders)          63701
28        order date (DateOrders)          65752
29                       Order Id          65752
33                  Order Item Id         180519

In [15]:
constant_cols = []

for col in df.columns:
    if df[col].nunique() == 1:
        constant_cols.append(col)

constant_cols

['Customer Email', 'Customer Password', 'Product Status']

In [16]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [17]:
(df["Product Card Id"] == df["Order Item Cardprod Id"]).all()

np.True_

# Exploratory Data Profiling

In [19]:
def explore_column(column):
    print(f"\n{'='*50}")
    print(f"Column: {column}")
    print(f"{'='*50}")
    print(df[column].value_counts(dropna=False))

In [20]:
explore_column("Delivery Status")

==================================================
Column: Delivery Status
==================================================
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [21]:
explore_column("Shipping Mode")

==================================================
Column: Shipping Mode
==================================================
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [22]:
explore_column("Market")

==================================================
Column: Market
==================================================
Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

In [23]:
explore_column("Order Status")

==================================================
Column: Order Status
==================================================
Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

In [24]:
explore_column("Customer Segment")

==================================================
Column: Customer Segment
==================================================
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [25]:
explore_column("Type")

==================================================
Column: Type
==================================================
Type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64